### ISSUE TITLE
Missing ACT event id 41

### ISSUE THREAD

**Issue by nonowazu** [xivlogs/nari#60]
**Describe the bug**
ACT ID 41 isn't recognized by nari. Here's some sample line(s) from an ACT log file:

```
41|2022-02-09T20:12:47.4280000-06:00|8003759E|267B|00|00|E0000000|fe464ebc1b31b6d4
41|2022-02-09T20:13:51.3740000-06:00|8003759E|267C|3DCDF00|20|19946D90|2d73dd43f17c571b
41|2022-02-09T20:18:05.6180000-06:00|8003759E|267C|3D62000|7FCF|3D63048|25b3eb6dde254335
```

**To Reproduce**
```python
from nari.io.reader.actlog import ActLogReader
from sys import argv

for event in ActLogReader(argv[1], raise_on_checksum_failure=True, raise_on_invalid_id=True):
    pass
```

Where `argv[1]` points to a valid act log fle.

**Expected behaviour**
No raised exception.

**Screenshots or Stack Traces**
```
Traceback (most recent call last):
  File "/Users/nono/Projects/nari/basic_parsing.py", line 4, in <module>
    for event in ActLogReader(argv[1], raise_on_checksum_failure=True, raise_on_invalid_id=True):
  File "/Users/nono/Projects/nari/nari/io/reader/__init__.py", line 15, in __next__
    event: Optional[Event] = self.read_next()
  File "/Users/nono/Projects/nari/nari/io/reader/actlog.py", line 61, in read_next
    if (event := self.handle_line(line)) is not None:
  File "/Users/nono/Projects/nari/nari/io/reader/actlog.py", line 30, in handle_line
    raise EventNotFound(f"ACT id: {id_}")
nari.util.exceptions.EventNotFound: ACT id: 41
```

**System (please complete the following information):**
head of `event-rewrite` branch

**Additional context**
More events to parse I guess.

**Comment by ayyaruq** [comment]
This is what ACT calls `SystemLogMessage`, it has an ID and 3 params. The ID is a direct reference to the `LogMessage` EXD, and the params tell the client how to format it. Looking at the contents of the messages, I don't see why ACT needs to know these, we can no-op it.
